{"name": "test_06", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 3", "trace": "def test_06():\n        print(\"test_3\")\n>       assert 1==3\nE       assert 1 == 3\n\n..\\test_case\\test_case_02.py:16: AssertionError"}, "attachments": [{"name": "stdout", "source": "21c2533a-b7d8-4d99-9372-a94162b79c19-attachment.txt", "type": "text/plain"}], "start": 1585014187935, "stop": 1585014187936, "uuid": "1cb43429-30d5-4bc3-86f3-dbc086392495", "historyId": "83494d0f6df0eee6b7f94710da351918", "testCaseId": "2c404975c1ea3fb1c77f7bac79d7a6d1", "fullName": "test_case.test_case_02#test_06", "labels": [{"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_case_02"}, {"name": "host", "value": "SC-201906191310"}, {"name": "thread", "value": "6524-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_case_02"}]}