{"name": "test_03", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 3", "trace": "def test_03():\n        print(\"test_3\")\n>       assert 1==3\nE       assert 1 == 3\n\n..\\test_case\\test_case_01.py:16: AssertionError"}, "attachments": [{"name": "stdout", "source": "23ea92e7-f5da-454f-9de7-f805bcd16f1a-attachment.txt", "type": "text/plain"}], "start": 1585014187911, "stop": 1585014187912, "uuid": "26cc6dfe-c2a5-4a56-b036-f611cca324ca", "historyId": "eac148731659511a8a2420eefbfd418b", "testCaseId": "a2df642b60164aaf429746a4207bf5e6", "fullName": "test_case.test_case_01#test_03", "labels": [{"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_case_01"}, {"name": "host", "value": "SC-201906191310"}, {"name": "thread", "value": "6524-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_case_01"}]}