{"name": "test_05", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "def test_05():\n        print(\"test_2\")\n>       assert 1==2\nE       assert 1 == 2\n\n..\\test_case\\test_case_02.py:12: AssertionError"}, "attachments": [{"name": "stdout", "source": "6606fd92-caad-45ce-9ea6-539282b0fb9e-attachment.txt", "type": "text/plain"}], "start": 1585014187927, "stop": 1585014187927, "uuid": "a444f3c8-da1d-4e76-b576-e2272bfdf291", "historyId": "d0e37341b72ef53d3f9c9c866dd2c195", "testCaseId": "297fd299acb3c7cc4cf044ff1417e61d", "fullName": "test_case.test_case_02#test_05", "labels": [{"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_case_02"}, {"name": "host", "value": "SC-201906191310"}, {"name": "thread", "value": "6524-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_case_02"}]}